version: '2.4'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 3000:3000
    restart: always
  # back:
  #   build:
  #     context: ./back/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3001:3000
  #   restart: always
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     db:
  #       condition: service_started

  # db:
  #   image: postgres:15
  #   restart: always
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pg_data:/var/lib/postgresql

volumes:
  pg_data:
