version: '2.4'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    expose:
      - 3000:3000
    restart: always

  back:
    build:
      context: ./back/
      dockerfile: Dockerfile
    expose:
      - 3000:3001
    restart: always
    env_file:
      - ./back/.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: uhuu_delivery
      MYSQL_USER: myuser
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_PASSWORD: mypass
