version: '2.4'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    expose:
      - 3000:3000
    restart: always

  back:
    build:
      context: ./back/
      dockerfile: Dockerfile
    expose:
      - 3000:3001
    restart: always
    env_file:
      - ./back/.env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - 25432:5432
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: uhuu
      POSTGRES_PASS: uhuu
      POSTGRES_DBNAME: delivery
