export type NominatimSearchResponse = NominatimSearchItem[];

// Generated by https://quicktype.io
export interface NominatimSearchItem {
  place_id: number;
  licence: string;
  osm_type: string;
  osm_id: number;
  boundingbox: string[];
  lat: string;
  lon: string;
  display_name: string;
  class: string;
  type: string;
  importance: number;
  address: {
    road: string;
    city?: string;
    municipality: string;
    state_district: string;
    state: string;
    "ISO3166-2-lvl4": string;
    region: string;
    postcode: string;
    country: string;
    country_code: string;
    town?: string;
  };
}
